export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_SUCESS = 'FETCH_COMMENTS_SUCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';